#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-Radius-SSG
version:      0.01
version_from: SSG.pm
installdirs:  site
requires:
    Net::Radius::Dictionary:       1.43
    Net::Radius::Packet:           1.44
    Net::UDP:                      1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.13
